language: node_js

cache:
  directories:
    - node_modules

node_js:
  - 6

install:
  - npm install
  - git reset --hard

script:
  - react-scripts build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $token
  on:
    branch: master

env:
  global:
